---
- name: Prepare dir ~/sw-pkg
  file: dest=/home/{{current_user}}/sw-pkg state=directory

- name: Prepare dir ~/App
  file: dest=/home/{{current_user}}/App state=directory

- name: Download ant
  get_url: url=http://mirrors.hust.edu.cn/apache//ant/binaries/apache-ant-1.9.4-bin.tar.gz dest=/home/{{ current_user }}/sw-pkg/apache-ant-bin.tar.gz

- name: unarchive
  unarchive: src=/home/{{ current_user }}/sw-pkg/apache-ant-bin.tar.gz dest=/home/{{current_user}}/App/

- name: Configure ANT_HOME
  lineinfile: dest=/home/{{ current_user }}/{{ rcfile }} line="export JAVA_HOME=/home/{{current_user}}/App/apache-ant-1.9.4"
