---
- name: Prepare dir ~/sw-pkg
  file: dest=/home/{{current_user}}/sw-pkg owner={{current_user}} group={{current_user}} state=directory

- name: Prepare dir ~/App
  file: dest=/home/{{current_user}}/App owner={{current_user}} group={{current_user}} state=directory

- name: Download ant
  get_url: url=http://mirrors.hust.edu.cn/apache//ant/binaries/apache-ant-1.9.4-bin.tar.gz dest=/home/{{ current_user }}/sw-pkg/apache-ant-bin.tar.gz

- name: unarchive
  unarchive: src=/home/{{ current_user }}/sw-pkg/apache-ant-bin.tar.gz dest=/home/{{current_user}}/App/

- name: Configure JAVA_HOME
  lineinfile: dest=/home/{{ current_user }}/{{ rcfile }} line="export JAVA_HOME=/usr/lib/jvm/java-1.7.0"

- name: Configure ANT_HOME
  lineinfile: dest=/home/{{ current_user }}/{{ rcfile }} line="export ANT_HOME=/home/{{current_user}}/App/apache-ant-1.9.4"

- name: Configure ANT_HOME/bin to PATH
  lineinfile: dest=/home/{{ current_user }}/{{ rcfile }} line="export PATH=\"/home/{{current_user}}/App/apache-ant-1.9.4/bin:$PATH\""

- name: fetch ant lib
  shell: source /home/{{current_user}}/{{rcfile}} && cd $ANT_HOME && ant -f fetch.xml -Ddest=system
