---
- name: Download ant
  get_url: url=http://mirrors.hust.edu.cn/apache//ant/binaries/apache-ant-1.9.4-bin.tar.gz dest=/home/{{ current_user }}/sw-pkg/apache-ant-bin.tar.gz

- name: unarchive
  unarchive: src=/home/{{ current_user }}/sw-pkg/apache-ant-bin.tar.gz dest=/home/{{current_user}}/App/
